### ISSUE TITLE
cargo install fails

### ISSUE THREAD

**Issue by olson-dan** [gimli-rs/ddbug#24]
There is a compile error at head.

>cargo --version
cargo 1.34.0 (6789d8a0a 2019-04-01)

>cargo install --git https://github.com/gimli-rs/ddbug
```
   Compiling ddbug v0.2.0 (https://github.com/gimli-rs/ddbug#8c162c40)
error[E0106]: missing lifetime specifier
   --> C:\Users\dolson\.cargo\git\checkouts\ddbug-36c848acbe6c76f0\8c162c4\main\src\code.rs:108:9
    |
108 |     cs: capstone::Capstone,
    |         ^^^^^^^^^^^^^^^^^^ expected lifetime parameter

error: aborting due to previous error
```

**Comment by philipc** [comment]
Hmm, looks like `cargo install` was ignoring the patches in the workspace Cargo.toml. I've removed them, please try again now.

**Comment by olson-dan** [comment]
Confirmed that it works for me now, thanks!
