### ISSUE TITLE
Expose base type encodings

### ISSUE THREAD

**Issue by RReverser** [gimli-rs/ddbug#25]
Base type names differ between different languages, but they're described fairly precisely via `DW_AT_encoding` + `DW_AT_endianity` + bit size and offset.

It would be great if `ddbug` would add ability to print these layout details of base types both in API and CLI.

**Comment by philipc** [comment]
Sure we can do that. I hadn't been interested in them because they don't change for a given language/platform.

**Comment by philipc** [comment]
Added basic support in a0355aa (endianity and some encodings only). Do you have examples of languages that use bit size and offset, or other encodings?

**Comment by RReverser** [comment]
Not sure about bit size, but byte size is definitely a thing as e.g. `int` vs `short int` are both encoded with `DW_ATE_signed` but differ only in `DW_AT_byte_size` value.

**Comment by RReverser** [comment]
(That was quick btw!)

**Comment by philipc** [comment]
Ah yeah byte size is done too, all types have that. It already used to display base types, but I filtered them out, so I only had to add support for the new attributes.
