### ISSUE TITLE
two dimens array & bit size error

### ISSUE THREAD

**Issue by diguasange** [gimli-rs/ddbug#34]
Hi ，I found a problem, may need attention
**test:**
typedef struct
{
    /* data */
    char name;
    short int aaaaa[5];
    short int bbb[2][3];
    short int proType1:4;
    short int proType2:10;

}test_elf;

**result:**
type test_elf = struct <anon>
	size: 26
	members:
		0[1]	name: char
		1[1]	<padding>
		2[10]	aaaaa: [short int; 5]
		12[6]	bbb: [short int; 3]**//size should be 12,not 6,and rows=2,cols=3 can show?**
		18[6]	<padding>
		24[0.4]	proType1: short int**//size should be 0.5byte**
		24.4[1.2]	proType2: short int**//1.25byte**
		25.6[0.2]	<padding>**//0.25byte**

**Comment by philipc** [comment]
Thanks for the report.

>  12[6] bbb: [short int; 3]//size should be 12,not 6,and rows=2,cols=3 can show?

Yes that's a bug. I'll work on a fix for that.

> 24[0.4] proType1: short int**//size should be 0.5byte**
> 24.4[1.2] proType2: short int**//1.25byte**
> 25.6[0.2] **//0.25byte**

These are all intentional. These aren't decimal numbers. Instead, the number after the period is the number of bits.

**Comment by diguasange** [comment]
Looking forward to your new change!
Besides, "the number after the period is the number of bits.",If so,
24[0.4] proType1: short int
24.4[1.2] proType2: short int**//should be 1.0 not 1.2 ,10bit?**
25.6[0.2] **//0.2 for padding**

**Comment by diguasange** [comment]
> 1.2 means 1 byte and 2 bits, for a total of 10 bits.

Got it, thanks!

**Comment by philipc** [comment]
Fixed in 8dd5ab60d893c6680390155eeda9acecc0cf4b71
