### ISSUE TITLE
Version bump request

### ISSUE THREAD

**Issue by jebradbury39** [gimli-rs/ddbug#39]
There's been some breaking API changes since the last release, for example:

https://docs.rs/ddbug_parser/0.3.0/ddbug_parser/struct.Function.html#method.range

This function has now been replaced by `ranges`.

Would this warrant a new version (e.g. `0.4.0`)? Currently, I'm just using the git repo instead of the published 0.3.0 (the published version also has some old wasm dependency that results in a deprecation warning every time you build).

**Comment by philipc** [comment]
I can publish a version if it helps you. Currently this crate is only passively maintained.

**Comment by jebradbury39** [comment]
That would be great! I figured that the crate isn't getting many active changes, but it will be nice to have the online docs match the latest code, along with being able to use the published version rather than pulling in the repo directly.

**Comment by philipc** [comment]
Published 0.4.0
