### ISSUE TITLE
Improve Function Arg/Var Location

### ISSUE THREAD

**Issue by SWW13** [gimli-rs/ddbug#41]
I'd like to print function arguments and local variables during a programs execution.

It looks like the required information is available in [`function.rs#L257-L258`](https://github.com/gimli-rs/ddbug/blob/master/parser/src/function.rs#L257-L258) and [`variable.rs#L170`](https://github.com/gimli-rs/ddbug/blob/master/parser/src/variable.rs#L170-L170).
However they are only exposed through `registers`, `register_offsets` and `frame_locations` ([`function.rs#L287-L300`](https://github.com/gimli-rs/ddbug/blob/master/parser/src/function.rs#L287-L300), [`variable.rs#L219-L246`](https://github.com/gimli-rs/ddbug/blob/master/parser/src/variable.rs#L219-L246)) which comes with some downsides:
- To figuring out the currently valid location all these functions have to be checked
  - `frame_locations` does not include the range (no way to figure out if it's valid)
- Other value locations are missing (value, literal or optimized out values are not accessible)

I think including the range in `Piece` and exposing it would be enough to solve all the issues above.

**Comment by philipc** [comment]
Depending on your needs, maybe `Piece` isn't enough either, because it still doesn't include all locations; for some we give up and return [`Location::Other`] instead.

What's your use case? It sounds roughly like a debugger? For a debugger, I expect you would be better off using `gimli` directly, so that you can evaluate the DWARF expression without loss of information.

**Comment by SWW13** [comment]
That would be fine, it's currently intended as an best effort with no guarantees.

It's roughly a non-interactive debugger. I'm doing emulation and would like to print function arguments and structs at a given memory location. Being able to print args / vars for each instruction would be a nice cherry on top.

While this crate does not perfectly fit my needs, it's a lot less work than starting from scratch. I'm also not looking for a perfect solution just something that's good enough and works in most cases.

**Comment by philipc** [comment]
> I think including the range in Piece

So we could do that, and there's TODO saying we should but I don't remember why and can't see a reason.

I think it would be okay to simply add the following, unless you think we need something different:
```rust
pub fn locations(&self) -> &[(Range, Piece)] {
    &self.locations
}
```

**Comment by SWW13** [comment]
> So we could do that, and there's TODO saying we should [...]

That's why I suggested it.

Yeah, `locations` with a `Range` and `Piece` pair should perfectly cover my use case.

**Comment by philipc** [comment]
Added in fff03bcebdc11822bdc3a88f730d7da462fbc7f5
